"""
api.py
======
Internal FastAPI service to expose the Advanced RAG retrieval pipeline as an
OpenAPI tool for the ARK multi-agent team.

Features:
- PII sanitization of incoming queries and outgoing context
- Langfuse tracing & OpenTelemetry integration
- Retrieval confidence scoring

Run with:
    uvicorn api:app --port 8000
"""

from __future__ import annotations

import os
from typing import Any

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field
from langfuse.decorators import observe, langfuse_context
from opentelemetry.instrumentation.fastapi import FastAPIInstrumentor

from config import settings
from retrievers.hybrid import HybridRetriever
from retrievers.reranker import BGEReranker
from utils import get_logger, pii_masking_service

log = get_logger(__name__)

# Bootstrapping Langfuse ENV variables
os.environ.setdefault("LANGFUSE_SECRET_KEY", settings.langfuse_secret_key)
os.environ.setdefault("LANGFUSE_PUBLIC_KEY", settings.langfuse_public_key)
os.environ.setdefault("LANGFUSE_HOST", settings.langfuse_base_url)

app = FastAPI(
    title="HR Policy Retrieval API",
    description="Tool interface for ARK agents to search the HR knowledge base.",
    version="1.0.0",
)

# OpenTelemetry Tracing
FastAPIInstrumentor.instrument_app(app)

# Singletons for retrievers (loaded lazily on first request or explicitly here)
_retriever = None
_reranker = None

def get_retriever():
    global _retriever
    if _retriever is None:
        _retriever = HybridRetriever()
    return _retriever

def get_reranker():
    global _reranker
    if _reranker is None:
        _reranker = BGEReranker()
    return _reranker


# ---------------------------------------------------------------------------
# API Models
# ---------------------------------------------------------------------------

class SearchQuery(BaseModel):
    query: str = Field(..., description="The search query generated by the router agent.")

class SearchResultChunk(BaseModel):
    text: str = Field(..., description="The retrieved policy text.")
    document: str = Field(..., description="The source document name.")
    section: str = Field(..., description="The document section, if available.")
    score: float = Field(..., description="Relevance score.")

class SearchResponse(BaseModel):
    results: list[SearchResultChunk]
    confidence: float
    status: str = Field(..., description="'success' or 'insufficient_information'")


# ---------------------------------------------------------------------------
# API Endpoints
# ---------------------------------------------------------------------------

@app.post("/search_hr_policies", response_model=SearchResponse)
@observe(name="search_hr_policies_tool")
def search_hr_policies(req: SearchQuery) -> SearchResponse:
    """
    Search the existing HR policy knowledge base and return the most relevant
    policy information for an employee question.
    """
    original_query = req.query
    
    # 1. PII Sanitization (Runtime Input)
    sanitized_query = pii_masking_service.sanitize_text(original_query)
    
    log.info("search_tool_called", query_preview=sanitized_query[:80])
    langfuse_context.update_current_observation(input=sanitized_query)
    
    try:
        retriever = get_retriever()
        reranker = get_reranker()
        
        # 2. Hybrid Retrieval
        candidate_docs = retriever.retrieve(sanitized_query, k=settings.retrieval_top_k)
        
        if not candidate_docs:
            response = SearchResponse(results=[], confidence=0.0, status="insufficient_information")
            langfuse_context.update_current_observation(output=response.model_dump())
            return response
            
        # 3. Reranking
        reranked_docs = reranker.rerank(sanitized_query, candidate_docs, top_n=settings.reranker_top_n)
        
        if not reranked_docs:
            response = SearchResponse(results=[], confidence=0.0, status="insufficient_information")
            langfuse_context.update_current_observation(output=response.model_dump())
            return response

        # 4. Confidence Calculation
        # BGE-reranker outputs raw logits. For this model, logits > 0 generally
        # indicate relevance, but we can map it to a proxy confidence.
        top_score = reranked_docs[0].metadata.get("rerank_score", 0.0)
        
        # Basic mapping: logit -2..+5 mapped to 0..1
        confidence = max(0.0, min(1.0, (top_score + 2.0) / 7.0))
        
        if confidence < 0.2:
            response = SearchResponse(results=[], confidence=round(confidence, 2), status="insufficient_information")
            langfuse_context.update_current_observation(output=response.model_dump())
            return response

        # 5. Format Output & Sanitize Context
        results = []
        for doc in reranked_docs:
            # Runtime Context Sanitization: Ensure no sensitive info leaked
            safe_text = pii_masking_service.sanitize_text(doc.page_content)
            
            results.append(SearchResultChunk(
                text=safe_text,
                document=doc.metadata.get("source", "HR Policy Guide"),
                section=doc.metadata.get("section", "General"),
                score=doc.metadata.get("rerank_score", 0.0)
            ))
            
        response = SearchResponse(
            results=results,
            confidence=round(confidence, 2),
            status="success"
        )
        
        langfuse_context.update_current_observation(output=response.model_dump())
        return response

    except Exception as e:
        log.exception("search_tool_failed", error=str(e))
        raise HTTPException(status_code=500, detail="HR Policy retrieval temporarily unavailable.")
